# Generated by Django 4.2.6 on 2023-10-17 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_membro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('classificacao', models.IntegerField()),
                ('duracao', models.TimeField()),
                ('sinopse', models.TextField()),
                ('produtora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produtora')),
            ],
        ),
    ]
